/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Lucy
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        //Maximar a tela
        this.setExtendedState(MAXIMIZED_BOTH);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        lblTaxi = new javax.swing.JLabel();
        mnbPrincipal = new javax.swing.JMenuBar();
        mnSignUp = new javax.swing.JMenu();
        mntClient = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mntTickets = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mntExit = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        mnAbout = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Taxi");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/Taxi_Right_Yellow_26335 (1).png")).getImage());
        setIconImages(null);

        lblTaxi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaxi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/42550oncomingtaxi_99104.png"))); // NOI18N
        lblTaxi.setToolTipText("");
        lblTaxi.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        mnbPrincipal.setName(""); // NOI18N

        mnSignUp.setMnemonic('s');
        mnSignUp.setText("Sign Up");

        mntClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/manager_person_man_people_2841.png"))); // NOI18N
        mntClient.setMnemonic('c');
        mntClient.setText("Client");
        mntClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntClientActionPerformed(evt);
            }
        });
        mnSignUp.add(mntClient);
        mnSignUp.add(jSeparator1);

        mntTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/communication_assistance_help_support_service_information_icon_230472.png"))); // NOI18N
        mntTickets.setMnemonic('t');
        mntTickets.setText("Tickets");
        mntTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntTicketsActionPerformed(evt);
            }
        });
        mnSignUp.add(mntTickets);
        mnSignUp.add(jSeparator3);

        mntExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vcsconflicting_93497.png"))); // NOI18N
        mntExit.setMnemonic('e');
        mntExit.setText("Exit");
        mntExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntExitActionPerformed(evt);
            }
        });
        mnSignUp.add(mntExit);

        mnbPrincipal.add(mnSignUp);

        mnHelp.setMnemonic('h');
        mnHelp.setText("Help");
        mnbPrincipal.add(mnHelp);

        mnAbout.setMnemonic('a');
        mnAbout.setText("About");
        mnbPrincipal.add(mnAbout);

        setJMenuBar(mnbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTaxi, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTaxi, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mntClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntClientActionPerformed
        new SignUpClient().setVisible(true);        
    }//GEN-LAST:event_mntClientActionPerformed

    private void mntExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntExitActionPerformed
        //Sair da execução
        System.exit(0);
        
    }//GEN-LAST:event_mntExitActionPerformed

    private void mntTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntTicketsActionPerformed
        new SignUpTickets().setVisible(true);
    }//GEN-LAST:event_mntTicketsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel lblTaxi;
    private javax.swing.JMenu mnAbout;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenu mnSignUp;
    private javax.swing.JMenuBar mnbPrincipal;
    private javax.swing.JMenuItem mntClient;
    private javax.swing.JMenuItem mntExit;
    private javax.swing.JMenuItem mntTickets;
    // End of variables declaration//GEN-END:variables
}
