/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import taxi.Cliente;

/**
 *
 * @author Lucy
 */
public class SignUpClient extends javax.swing.JFrame {
    
    static ArrayList<Cliente> listaCliente;
    
    String botao;
    
    /**
     * Creates new form SignUpClient
     */
    public SignUpClient() {
        initComponents();
        
        listaCliente = new ArrayList();
        
        
        //Habilitar ou desabilitar botões
        bntNovo.setEnabled(true);
        bntPesquisar.setEnabled(true);
        bntAlterar.setEnabled(false);
        bntExcluir.setEnabled(false);
        bntSalvar.setEnabled(false);
        bntCancelar.setEnabled(false);
        bntOk.setEnabled(false);
        
        //Habilitar ou desabilitar txt/cmb
        txtId.setEnabled(false);
        txtRg.setEnabled(false);
        txtCpf.setEnabled(false);
        txtNome.setEnabled(false);
        txtTelefone.setEnabled(false);
        cmbChamado.setEnabled(false);
        
    }
    //Carregar tabela com clientes da lista
    public void carregarTabelaCliente(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Id","Rg","Cpf","Nome","Telefone"},0);
        
        for (int i=0;i<listaCliente.size();i++) {
            Object linha[] = new Object[]{listaCliente.get(i).getId(),
                                          listaCliente.get(i).getRg(),
                                          listaCliente.get(i).getCpf(),
                                          listaCliente.get(i).getNome(),
                                          listaCliente.get(i).getTelefone()};
            modelo.addRow(linha);
        }
        
        tblCliente.setModel(modelo);
        
        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(20);
        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(50);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDadoCliente = new javax.swing.JPanel();
        bntId = new javax.swing.JLabel();
        bntRg = new javax.swing.JLabel();
        bntCpf = new javax.swing.JLabel();
        bntNome = new javax.swing.JLabel();
        bntTelefone = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtRg = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        cmbChamado = new javax.swing.JComboBox<>();
        bntOk = new javax.swing.JButton();
        lblChamado = new javax.swing.JLabel();
        bntNovo = new javax.swing.JButton();
        bntPesquisar = new javax.swing.JButton();
        bntAlterar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        bntSalvar = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        bntExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlDadoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        bntId.setText("Id");

        bntRg.setText("Rg");

        bntCpf.setText("Cpf");

        bntNome.setText("Nome");

        bntTelefone.setText("Telefone");

        txtId.setToolTipText("Insira o id do cliente");

        txtRg.setToolTipText("Insira o rg do cliente");

        txtCpf.setToolTipText("Insira o cpf do cliente");

        txtNome.setToolTipText("Insira o nome do cliente");

        txtTelefone.setToolTipText("Insira o telefone do cliente");

        cmbChamado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um chamado", " " }));
        cmbChamado.setToolTipText("");

        bntOk.setText("Ok");
        bntOk.setToolTipText("Pesquisar cliente pelo CPF");

        lblChamado.setText("Chamado");

        javax.swing.GroupLayout pnlDadoClienteLayout = new javax.swing.GroupLayout(pnlDadoCliente);
        pnlDadoCliente.setLayout(pnlDadoClienteLayout);
        pnlDadoClienteLayout.setHorizontalGroup(
            pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadoClienteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadoClienteLayout.createSequentialGroup()
                        .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntRg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDadoClienteLayout.createSequentialGroup()
                        .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadoClienteLayout.createSequentialGroup()
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntOk))
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDadoClienteLayout.createSequentialGroup()
                        .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bntTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblChamado, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDadoClienteLayout.setVerticalGroup(
            pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadoClienteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntRg)
                    .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntOk))
                .addGap(8, 8, 8)
                .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChamado))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        bntNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/business_application_addmale_useradd_insert_add_user_client_2312.png"))); // NOI18N
        bntNovo.setText("Novo");
        bntNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNovoActionPerformed(evt);
            }
        });

        bntPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search_find_user_16727.png"))); // NOI18N
        bntPesquisar.setText("Pesquisar");

        bntAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/businessapplication_edit_male_user_thepencil_theclient_negocio_2321.png"))); // NOI18N
        bntAlterar.setText("Alterar");
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });

        bntExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete_delete_deleteusers_delete_male_user_maleclient_2348.png"))); // NOI18N
        bntExcluir.setText("Excluir");

        bntSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/businessapplication_accept_ok_male_man_you_negocio_2311.png"))); // NOI18N
        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        bntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vcsconflicting_93497.png"))); // NOI18N
        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Rg", "Cpf", "Nome", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);
        if (tblCliente.getColumnModel().getColumnCount() > 0) {
            tblCliente.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblCliente.getColumnModel().getColumn(1).setPreferredWidth(10);
            tblCliente.getColumnModel().getColumn(2).setPreferredWidth(20);
            tblCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblCliente.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        bntExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logout256_24927 (1).png"))); // NOI18N
        bntExit.setText("Exit");
        bntExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDadoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(bntNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bntCancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(bntExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntNovo)
                    .addComponent(bntPesquisar)
                    .addComponent(bntAlterar)
                    .addComponent(bntExcluir)
                    .addComponent(bntSalvar)
                    .addComponent(bntCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bntExitActionPerformed

    private void bntNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNovoActionPerformed
        botao = "novo";

        //Limpar os campos
        txtId.setText("");
        txtRg.setText("");
        txtCpf.setText("");
        txtNome.setText("");
        txtTelefone.setText("");

        //Habilitar ou desabilitar botões
        bntNovo.setEnabled(false);
        bntPesquisar.setEnabled(false);
        bntAlterar.setEnabled(false);
        bntExcluir.setEnabled(false);
        bntSalvar.setEnabled(true);
        bntCancelar.setEnabled(true);
        bntOk.setEnabled(false);
        
        //Habilitar ou desabilitar txt/cmb
        txtId.setEnabled(true);
        txtRg.setEnabled(true);
        txtCpf.setEnabled(true);
        txtNome.setEnabled(true);
        txtTelefone.setEnabled(true);
        cmbChamado.setEnabled(true);
        
        txtId.requestFocus();
        
    }//GEN-LAST:event_bntNovoActionPerformed

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
    
        if (txtId.getText().equals("") || 
                txtRg.getText().equals("") ||
                txtCpf.getText().equals("") ||
                txtNome.getText().equals("") ||
                txtTelefone.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Todos os campos devem ser inseridos","Mensagem", JOptionPane.INFORMATION_MESSAGE);
        } else {
            int id = Integer.parseInt(txtId.getText());
            String rg = txtRg.getText();
            long cpf = Long.parseLong(txtCpf.getText());
            String nome = txtNome.getText();
            int telefone = Integer.parseInt(txtTelefone.getText());
        
            if (botao.equals("novo")){
                Cliente cliente = new Cliente(id,rg,cpf,nome,telefone);
            
                //Adicionar cliente na lista
                listaCliente.add(cliente);
            
                JOptionPane.showMessageDialog(null,"Cliente cadastrado com sucesso","Mensagem", JOptionPane.INFORMATION_MESSAGE);
            } else if(botao.equals("editar")){
                int index = tblCliente.getSelectedRow();
                
                listaCliente.get(index).setId(id);
                listaCliente.get(index).setRg(rg);
                listaCliente.get(index).setCpf(cpf);
                listaCliente.get(index).setNome(nome);
                listaCliente.get(index).setTelefone(telefone);
            }
            
            //Carregar os dados do cliente na tabela
            carregarTabelaCliente();
            
            
            //Limpar os campos
            txtId.setText("");
            txtRg.setText("");
            txtCpf.setText("");
            txtNome.setText("");
            txtTelefone.setText("");

            //Habilitar ou desabilitar botões
            bntNovo.setEnabled(true);
            bntPesquisar.setEnabled(true);
            bntAlterar.setEnabled(false);
            bntExcluir.setEnabled(false);
            bntSalvar.setEnabled(false);
            bntCancelar.setEnabled(false);
            bntOk.setEnabled(false);

            //Habilitar ou desabilitar txt/cmb
            txtId.setEnabled(false);
            txtRg.setEnabled(false);
            txtCpf.setEnabled(false);
            txtNome.setEnabled(false);
            txtTelefone.setEnabled(false);
            cmbChamado.setEnabled(false);
        }
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
        //Limpar os campos
        txtId.setText("");
        txtRg.setText("");
        txtCpf.setText("");
        txtNome.setText("");
        txtTelefone.setText("");

        //Habilitar ou desabilitar botões
        bntNovo.setEnabled(true);
        bntPesquisar.setEnabled(true);
        bntAlterar.setEnabled(false);
        bntExcluir.setEnabled(false);
        bntSalvar.setEnabled(false);
        bntCancelar.setEnabled(false);
        bntOk.setEnabled(false);
        
        //Habilitar ou desabilitar txt/cmb
        txtId.setEnabled(false);
        txtRg.setEnabled(false);
        txtCpf.setEnabled(false);
        txtNome.setEnabled(false);
        txtTelefone.setEnabled(false);
        cmbChamado.setEnabled(false);
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        int i = tblCliente.getSelectedRow();
        
        if (i>=0 && i <listaCliente.size()){
            Cliente cli = listaCliente.get(i);
            txtId.setText(String.valueOf(cli.getId()));
            txtCpf.setText(String.valueOf(cli.getCpf()));
            txtRg.setText(String.valueOf(cli.getRg()));
            txtNome.setText(String.valueOf(cli.getCpf()));
            txtTelefone.setText(String.valueOf(cli.getTelefone()));
            
        }
        //Habilitar ou desabilitar botões
        bntNovo.setEnabled(true);
        bntPesquisar.setEnabled(true);
        bntAlterar.setEnabled(true);
        bntExcluir.setEnabled(true);
        bntSalvar.setEnabled(false);
        bntCancelar.setEnabled(false);
        bntOk.setEnabled(false);
        
        //Habilitar ou desabilitar txt/cmb
        txtId.setEnabled(false);
        txtRg.setEnabled(false);
        txtCpf.setEnabled(false);
        txtNome.setEnabled(false);
        txtTelefone.setEnabled(false);
        cmbChamado.setEnabled(false);
    }//GEN-LAST:event_tblClienteMouseClicked

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
        botao = "editar";


        //Habilitar ou desabilitar botões
        bntNovo.setEnabled(false);
        bntPesquisar.setEnabled(false);
        bntAlterar.setEnabled(false);
        bntExcluir.setEnabled(false);
        bntSalvar.setEnabled(true);
        bntCancelar.setEnabled(true);
        bntOk.setEnabled(false);
        
        //Habilitar ou desabilitar txt/cmb
        txtId.setEnabled(true);
        txtRg.setEnabled(true);
        txtCpf.setEnabled(true);
        txtNome.setEnabled(true);
        txtTelefone.setEnabled(true);
        cmbChamado.setEnabled(true);
        
        txtId.requestFocus();
    }

    private void bntOkActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_bntOkActionPerformed
        if (txtCpf.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo Cpf deve ser informado", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        } else{
            Cliente cli;
            String id = "", rg = "", cpf = "",nome = "",telefone = "";
            int pf = Integer.parseInt(txtCpf.getText());
            
            for (int i=0;i<listaCliente.size();i++){
                cli = listaCliente.get(i);
                
                if(pf == cli.getCpf()){
                    id = String.valueOf(cli.getId());
                    rg = cli.getRg();
                    cpf = String.valueOf(cli.getCpf());
                    nome = String.valueOf(cli.getNome());
                    telefone = String.valueOf(cli.getTelefone());
                }
            }
            
            txtCpf.setText(cpf);
        }       
        
    }
    
    private void bntPesquisarActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_bntPesquisarActionPerformed
        if (listaCliente.isEmpty()){
           JOptionPane.showMessageDialog(null,"Nenhum cliente está cadastrado","Mensagem", JOptionPane.PLAIN_MESSAGE);
       } else {
            //Limpar os campos
            txtId.setText("");
            txtCpf.setText("");
            txtNome.setText("");
            txtRg.setText("");
            txtTelefone.setText("");

            //Habilitar o desabilitar botões
            bntNovo.setEnabled(false);
            bntSalvar.setEnabled(false);
            bntAlterar.setEnabled(false);
            bntExcluir.setEnabled(false);
            bntOk.setEnabled(true);
            bntPesquisar.setEnabled(false);
            bntCancelar.setEnabled(true);

            //Habilitar e desabilitar campos de texto
            txtCpf.setEnabled(true);
            txtId.setEnabled(false);
            txtNome.setEnabled(false);
            txtRg.setEnabled(false);
            txtTelefone.setEnabled(false);

            txtCpf.requestFocus();
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntCancelar;
    private javax.swing.JLabel bntCpf;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntExit;
    private javax.swing.JLabel bntId;
    private javax.swing.JLabel bntNome;
    private javax.swing.JButton bntNovo;
    private javax.swing.JButton bntOk;
    private javax.swing.JButton bntPesquisar;
    private javax.swing.JLabel bntRg;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JLabel bntTelefone;
    private javax.swing.JComboBox<String> cmbChamado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChamado;
    private javax.swing.JPanel pnlDadoCliente;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRg;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
