/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import taxi.Chamados;

/**
 *
 * @author Lucy
 */
public class SignUpTickets extends javax.swing.JFrame {

    static ArrayList<Chamados> listaChamados;
    
    String botao;

    /**
     * Creates new form SignUpTickets
     */
    public SignUpTickets() {
        initComponents();
        
        
        listaChamados = new ArrayList();
        
        //Habilitar ou desabilitar botões
        bntNovo.setEnabled(true);
        bntAlterar.setEnabled(false);
        bntExcluir.setEnabled(false);
        bntSalvar.setEnabled(false);
        bntPesquisar.setEnabled(true);
        bntOk.setEnabled(false);
        bntCancelar.setEnabled(false);
        
        //Habilitar ou desabiltar campo de texto
        txtId.setEnabled(false);
        txtData.setEnabled(false);
        txtDestino.setEnabled(false);
        txtOrigem.setEnabled(false);
        txtTipo.setEnabled(false);
    }

    // Carregar a tabela com chamados da lista
    public void carregarTabelaChamados(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"ID","Data","Tipo","Origem","Destino"},0);
        
        for (int i=0;i<listaChamados.size();i++){
            Object linha[] = new Object[]{listaChamados.get(i).getIdChamado(),
                                           listaChamados.get(i).getDataChamado(),
                                           listaChamados.get(i).getTipoChamado(),
                                           listaChamados.get(i).getOrigemChamado(),
                                           listaChamados.get(i).getDestinoChamado()};
            modelo.addRow(linha);
            
        }
        
        //Tabela recebe model
        tblChamados.setModel(modelo);
        
        tblChamados.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblChamados.getColumnModel().getColumn(1).setPreferredWidth(5);
        tblChamados.getColumnModel().getColumn(2).setPreferredWidth(20);
        tblChamados.getColumnModel().getColumn(3).setPreferredWidth(55);
        tblChamados.getColumnModel().getColumn(4).setPreferredWidth(55);
    }    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblOrigem = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtOrigem = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        bntOk = new javax.swing.JButton();
        txtTipo = new javax.swing.JTextField();
        bntPesquisar = new javax.swing.JButton();
        bntAlterar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        bntSalvar = new javax.swing.JButton();
        bntNovo = new javax.swing.JButton();
        JScrollPane = new javax.swing.JScrollPane();
        tblChamados = new javax.swing.JTable();
        btnSair = new javax.swing.JButton();
        bntCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sign Up of Tickets");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tickets", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel1.setName("Tickets"); // NOI18N

        lblID.setText("ID:");

        lblData.setText("Data:");

        lblTipo.setText("Tipo:");

        lblOrigem.setText("Origem:");

        lblDestino.setText("Destino:");

        txtId.setToolTipText("Insira o código do Chamado");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtData.setToolTipText("Insira a data de criação do chamado");
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        txtOrigem.setToolTipText("Insira a origem da sua partida");
        txtOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrigemActionPerformed(evt);
            }
        });

        txtDestino.setToolTipText("Insira o destino da sua partida");
        txtDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDestinoActionPerformed(evt);
            }
        });

        bntOk.setText("OK");
        bntOk.setToolTipText("Pesquisar chamado pelo código");
        bntOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntOk))
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntOk))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrigem)
                    .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDestino))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        bntPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file-search_114412.png"))); // NOI18N
        bntPesquisar.setText("Pesquisar");
        bntPesquisar.setToolTipText("Pesquisar o chamado");
        bntPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesquisarActionPerformed(evt);
            }
        });

        bntAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file-edit_114433.png"))); // NOI18N
        bntAlterar.setText("Alterar");
        bntAlterar.setToolTipText("Alterar os dados do chamado");
        bntAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlterarActionPerformed(evt);
            }
        });

        bntExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/file-delete_114438.png"))); // NOI18N
        bntExcluir.setText("Excluir");
        bntExcluir.setToolTipText("Excluir o chamado");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        bntSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save_37110.png"))); // NOI18N
        bntSalvar.setText("Salvar");
        bntSalvar.setToolTipText("Salvar o chamado");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        bntNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/new-file_40454.png"))); // NOI18N
        bntNovo.setText("Novo");
        bntNovo.setToolTipText("Inserir um novo chamado");
        bntNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNovoActionPerformed(evt);
            }
        });

        JScrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JScrollPaneMouseClicked(evt);
            }
        });

        tblChamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Tipo", "Origem", "Destino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblChamados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChamadosMouseClicked(evt);
            }
        });
        JScrollPane.setViewportView(tblChamados);
        if (tblChamados.getColumnModel().getColumnCount() > 0) {
            tblChamados.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblChamados.getColumnModel().getColumn(1).setResizable(false);
            tblChamados.getColumnModel().getColumn(1).setPreferredWidth(5);
            tblChamados.getColumnModel().getColumn(2).setPreferredWidth(7);
            tblChamados.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblChamados.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logout256_24927 (1).png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setToolTipText("Fechar janela");
        btnSair.setFocusPainted(false);
        btnSair.setRequestFocusEnabled(false);
        btnSair.setRolloverEnabled(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        bntCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vcsconflicting_93497.png"))); // NOI18N
        bntCancelar.setText("Cancelar");
        bntCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntCancelar))
            .addGroup(layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(btnSair))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntPesquisar)
                    .addComponent(bntSalvar)
                    .addComponent(bntNovo)
                    .addComponent(bntCancelar)
                    .addComponent(bntExcluir)
                    .addComponent(bntAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        bntNovo.setEnabled(false);
        bntSalvar.setEnabled(true);
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        bntNovo.setEnabled(false);
        bntSalvar.setEnabled(true);
    }//GEN-LAST:event_txtDataActionPerformed

    private void bntPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesquisarActionPerformed
       if (listaChamados.isEmpty()){
           JOptionPane.showMessageDialog(null,"Nenhum chamado está cadastrado","Mensagem", JOptionPane.PLAIN_MESSAGE);
       } else {
           //Limpar os campos
        txtId.setText("");
        txtData.setText("");
        txtTipo.setText("");
        txtOrigem.setText("");
        txtDestino.setText("");

        //Habilitar o desabilitar botões
        bntNovo.setEnabled(false);
        bntSalvar.setEnabled(false);
        bntAlterar.setEnabled(false);
        bntExcluir.setEnabled(false);
        bntOk.setEnabled(true);
        bntPesquisar.setEnabled(false);
        bntCancelar.setEnabled(true);
        
        //Habilitar e desabilitar campos de texto
        txtData.setEnabled(true);
        txtDestino.setEnabled(false);
        txtId.setEnabled(false);
        txtOrigem.setEnabled(false);
        txtTipo.setEnabled(false);
        
        txtData.requestFocus();
       }
    }//GEN-LAST:event_bntPesquisarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        //Fechar janela
        this.setVisible(false);
        
    }//GEN-LAST:event_btnSairActionPerformed

    private void bntNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNovoActionPerformed
        botao = "novo";
        
        //Limpar os campos
        txtId.setText("");
        txtData.setText("");
        txtTipo.setText("");
        txtOrigem.setText("");
        txtDestino.setText("");
            

        //Habilitar o desabilitar botões
        bntNovo.setEnabled(false);
        bntSalvar.setEnabled(true);
        bntAlterar.setEnabled(false);
        bntExcluir.setEnabled(false);
        bntOk.setEnabled(true);
        bntPesquisar.setEnabled(false);
        bntCancelar.setEnabled(true);
        
        //Habilitar e desabilitar campos de texto
        txtData.setEnabled(true);
        txtDestino.setEnabled(true);
        txtId.setEnabled(true);
        txtOrigem.setEnabled(true);
        txtTipo.setEnabled(true);
        
        
        txtId.requestFocus();
        
    }//GEN-LAST:event_bntNovoActionPerformed

    private void bntAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlterarActionPerformed
        botao = "editar";
        
        //Habiltiar e desabilitar botoes
        bntNovo.setEnabled(false);
        bntSalvar.setEnabled(true);
        bntAlterar.setEnabled(false);
        bntExcluir.setEnabled(false);
        bntOk.setEnabled(false);
        bntPesquisar.setEnabled(false);
        bntCancelar.setEnabled(true);
        
        //Habilitar e desabilitar campos de texto
        txtData.setEnabled(true);
        txtDestino.setEnabled(true);
        txtId.setEnabled(true);
        txtOrigem.setEnabled(true);
        txtTipo.setEnabled(true);
        
        txtId.requestFocus();
      
    }//GEN-LAST:event_bntAlterarActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        int index = tblChamados.getSelectedRow();
        
        if (index>=0 && index<listaChamados.size()){
            listaChamados.remove(index);
        }
        
        carregarTabelaChamados();
        
        //Limpar os campos
        txtId.setText("");
        txtData.setText("");
        txtTipo.setText("");
        txtOrigem.setText("");
        txtDestino.setText("");
         

        //Habilitar o desabilitar botões
        bntNovo.setEnabled(true);
        bntSalvar.setEnabled(false);
        bntAlterar.setEnabled(false);
        bntExcluir.setEnabled(false);
        bntOk.setEnabled(false);
        bntPesquisar.setEnabled(true);
        bntCancelar.setEnabled(false);
        
        //Habilitar e desabilitar campos de texto
        txtData.setEnabled(false);
        txtDestino.setEnabled(false);
        txtId.setEnabled(false);
        txtOrigem.setEnabled(false);
        txtTipo.setEnabled(false);
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        
       if (txtId.getText().equals("") || 
            txtData.getText().equals("") || 
            txtTipo.getText().equals("") || 
            txtOrigem.getText().equals("") || 
            txtDestino.getText().equals("")) {
           JOptionPane.showMessageDialog(null,"Todos os campos devem ser inseridos","Mensagem", JOptionPane.PLAIN_MESSAGE);
       }else {
            int id = Integer.parseInt(txtId.getText());
            int data = Integer.parseInt(txtData.getText());
            String tipo = txtTipo.getText();
            String origem = txtOrigem.getText();
            String destino = txtDestino.getText();
            
            if(botao.equals("novo")){
                Chamados chamados = new Chamados(id, data, tipo, origem, destino);

                listaChamados.add(chamados);

                JOptionPane.showMessageDialog(null, "Chamado cadastrado com sucesso!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);

           } else if (botao.equals("editar")) {
                int index = tblChamados.getSelectedRow();
                listaChamados.get(index).setIdChamado(id);
                listaChamados.get(index).setDataChamado(data);
                listaChamados.get(index).setTipoChamado(tipo);
                listaChamados.get(index).setOrigemChamado(origem);
                listaChamados.get(index).setDestinoChamado(destino);
            }
                
            

            //Carregar os dados do Chamado na tabela
            carregarTabelaChamados();

            //Limpar os campos
             txtId.setText("");
             txtData.setText("");
             txtTipo.setText("");
             txtOrigem.setText("");
             txtDestino.setText("");


            //Habilitar o desabilitar botões
            bntNovo.setEnabled(true);
            bntSalvar.setEnabled(false);
            bntAlterar.setEnabled(false);
            bntExcluir.setEnabled(false);
            bntOk.setEnabled(false);
            bntPesquisar.setEnabled(true);
            bntCancelar.setEnabled(false);

            //Habilitar e desabilitar campos de texto
            txtData.setEnabled(false);
            txtDestino.setEnabled(false);
            txtId.setEnabled(false);
            txtOrigem.setEnabled(false);
            txtTipo.setEnabled(false);
       
    }//GEN-LAST:event_bntSalvarActionPerformed
    }
    private void bntOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntOkActionPerformed
        if (txtData.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Campo data deve ser informado", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
        } else{
            Chamados datee;
            String data = "", destino = "",id = "",origem = "",tipo = "";
            int dat = Integer.parseInt(txtData.getText());
            
            
            for (int i=0; i <listaChamados.size(); i++){
                datee = listaChamados.get(i);
                
                if (dat == datee.getDataChamado()) {
                    data = String.valueOf(datee.getDataChamado());
                    destino = datee.getDestinoChamado();
                    id = String.valueOf(datee.getIdChamado());
                    origem = datee.getOrigemChamado();
                    tipo = datee.getTipoChamado();
                    
                }
        }
            if(data.equals("")) {
               JOptionPane.showMessageDialog(null, "Esta data não existe!", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
                txtDestino.setText("");
                txtId.setText("");
                txtOrigem.setText("");
                txtTipo.setText("");
            } else {
                txtData.setText(data);
                txtDestino.setText(destino);
                txtId.setText(id);
                txtOrigem.setText(origem);
                txtTipo.setText(tipo);

            }
            txtData.selectAll();
            txtData.requestFocus(); 
        }
    }//GEN-LAST:event_bntOkActionPerformed

    private void txtOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrigemActionPerformed
      
    }//GEN-LAST:event_txtOrigemActionPerformed

    private void txtDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoActionPerformed
     
    }//GEN-LAST:event_txtDestinoActionPerformed

    private void bntCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelarActionPerformed
         //Limpar os campos
         txtId.setText("");
         txtData.setText("");
         txtTipo.setText("");
         txtOrigem.setText("");
         txtDestino.setText("");
         

        //Habilitar o desabilitar botões
        bntNovo.setEnabled(true);
        bntSalvar.setEnabled(false);
        bntAlterar.setEnabled(false);
        bntExcluir.setEnabled(false);
        bntOk.setEnabled(false);
        bntPesquisar.setEnabled(true);
        bntCancelar.setEnabled(false);
        
        //Habilitar e desabilitar campos de texto
        txtData.setEnabled(false);
        txtDestino.setEnabled(false);
        txtId.setEnabled(false);
        txtOrigem.setEnabled(false);
        txtTipo.setEnabled(false);
       
        
    }//GEN-LAST:event_bntCancelarActionPerformed

    private void JScrollPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JScrollPaneMouseClicked
        
    }//GEN-LAST:event_JScrollPaneMouseClicked

    private void tblChamadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChamadosMouseClicked
        int i = tblChamados.getSelectedRow();
        
        if(i>=0 && i<listaChamados.size()){
            Chamados cha = listaChamados.get(i);
            txtId.setText(String.valueOf(cha.getIdChamado()));
            txtData.setText(String.valueOf(cha.getDataChamado()));
            txtTipo.setText(cha.getTipoChamado());
            txtOrigem.setText(cha.getOrigemChamado());
            txtDestino.setText(cha.getDestinoChamado());
    }
        //Habilitar o desabilitar botões
        bntNovo.setEnabled(true);
        bntSalvar.setEnabled(false);
        bntAlterar.setEnabled(true);
        bntExcluir.setEnabled(true);
        bntOk.setEnabled(false);
        bntPesquisar.setEnabled(true);
        bntCancelar.setEnabled(false);
        
        //Habilitar e desabilitar campos de texto
        txtData.setEnabled(false);
        txtDestino.setEnabled(false);
        txtId.setEnabled(false);
        txtOrigem.setEnabled(false);
        txtTipo.setEnabled(false);
    }//GEN-LAST:event_tblChamadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JButton bntAlterar;
    private javax.swing.JButton bntCancelar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntNovo;
    private javax.swing.JButton bntOk;
    private javax.swing.JButton bntPesquisar;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblOrigem;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable tblChamados;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtOrigem;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables

    private static class Data {

        public Data() {
        }
    }

    private static class Dataa {

        public Dataa() {
        }
    }

    
    }

    
        
